### PR TITLE
Generalizing LLM for completion and embedding

### PR DESCRIPTION
**Pull request by KienLau**
This pull request generalizes the LLM model for OpenAI (chatGPT3 to 4), Azure, Llama2, and Claude2 for embedding and completion. The user would need to just change the config file.

### CODE REVIEW

**Review by callanwu — COMMENTED** [review]
Provide a example which uses other model in config file(https://github.com/aiwaves-cn/agents/blob/master/examples/Single_Agent/chat_bot/config.json).

**Review by jianghuyihei — CHANGES_REQUESTED** [review]
We are not using LLM_ Type to control Embedding_ Model, but with an additional parameter Embed_ Model to control, we have already implemented it here

**Comment by KienLau** [comment]
> Provide a example which uses other model in config file(https://github.com/aiwaves-cn/agents/blob/master/examples/Single_Agent/chat_bot/config.json).

So every instance of
"LLM_type" : "Replicate" 
 "model" :  "replicate/llama-2-70b-chat:2796ee9483c3fd7aa2e171d38f4ca12251a30609463dcfd4cd76703f22e96cdf"

**Comment by KienLau** [comment]
> We are not using LLM_ Type to control Embedding_ Model, but with an additional parameter Embed_ Model to control, we have already implemented it here

So actually I think "Embed_Model" doesn't exist in os.environ so the embedding model will always default to "text-embedding-ada-002" (gpt3 embedding)

**Comment by callanwu** [comment]
> > Provide a example which uses other model in config file(https://github.com/aiwaves-cn/agents/blob/master/examples/Single_Agent/chat_bot/config.json).
> 
> So every instance of "LLM_type" : "Replicate" "model" : "replicate/llama-2-70b-chat:2796ee9483c3fd7aa2e171d38f4ca12251a30609463dcfd4cd76703f22e96cdf"

I mean changing the value of the "LLM_type" parameter is all that's needed to switch between different LLM instances. For example, setting "LLM_type" to "LLaMA-2" will automatically load the default instance associated with that type, which is "replicate/llama-2-70b-chat:2796ee9483c3fd7aa2e171d38f4ca12251a30609463dcfd4cd76703f22e96cdf", without requiring any additional configuration in the config file.

**Comment by callanwu** [comment]
> > We are not using LLM_ Type to control Embedding_ Model, but with an additional parameter Embed_ Model to control, we have already implemented it here
> 
> So actually I think "Embed_Model" doesn't exist in os.environ so the embedding model will always default to "text-embedding-ada-002" (gpt3 embedding)

We load "Embed_Model" to os.environ in https://github.com/aiwaves-cn/agents/blob/master/src/agents/SOP.py#L61C1-L63.

**Comment by KienLau** [comment]
> > > We are not using LLM_ Type to control Embedding_ Model, but with an additional parameter Embed_ Model to control, we have already implemented it here
> > 
> > 
> > So actually I think "Embed_Model" doesn't exist in os.environ so the embedding model will always default to "text-embedding-ada-002" (gpt3 embedding)
> 
> We load "Embed_Model" to os.environ in https://github.com/aiwaves-cn/agents/blob/master/src/agents/SOP.py#L61C1-L63.

Okay, I see. I changed the function to use "Embed_Model" (if it's in config) to specify the embedding model to use.

**Pull request closed without merging**
